
import { Customer, UserRole, CustomerLog, ChatChannel, ChatMessage, TeamMember, Notification, Language, SidebarPrefs } from '../types/types';

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard',
    customers: 'Customers',
    exploreAll: 'Explore All',
    customerDirectory: 'Customer Directory',
    totalRecords: 'Total Records',
    activeFilters: 'Active Filters',
    allStatuses: 'All Statuses',
    channels: 'Group Channels',
    directMessages: 'Direct Messages',
    quickNote: 'Quick Note',
    personalNotes: 'Personal Notes',
    searchPlaceholder: 'Search enterprise archives...',
    logout: 'Logout',
    accessLevel: 'Access Level',
    personnelDirectory: 'Personnel Directory',
    systemLive: 'System Live',
    activityFeed: 'Activity Feed',
    files: 'Files',
    archived: 'Archived',
    captureNote: 'Capture situational note...',
    saveArchive: 'Save Note to Nori Archives',
    privateEntry: 'Private Entry',
    caseStatus: 'Case Status',
    urgency: 'Urgency',
    assignTask: 'Assign Task',
    recentActivity: 'Recent Activity',
    activePersonnel: 'Active Personnel',
    criticalDeadlines: 'Critical Deadlines',
    language: 'Language',
    vietnamese: 'Vietnamese',
    english: 'English',
    postReply: 'Post Reply',
    editNote: 'Edit Note',
    saveNote: 'Save Note',
    discardChanges: 'Discard Changes',
    revisionHistory: 'Revision History',
    privateNote: 'Private Note',
    open: 'Open',
    resolved: 'Resolved',
    closed: 'Closed',
    low: 'Low',
    medium: 'Medium',
    high: 'High',
    urgent: 'Urgent',
    alerts: 'Alerts',
    clearAll: 'Clear All',
    noAlerts: 'No active alerts',
    intelligenceLogs: 'Intelligence Logs',
    urgentAlerts: 'Urgent Alerts',
    systemHealth: 'System Health',
    liveStream: 'Live Stream',
    noActivity: 'No activity found.',
    logBy: 'Log by',
    noDeadlines: 'No pending deadlines.',
    noAccessibleCustomers: 'No accessible customers found.',
    cancel: 'Cancel',
    saveQuickNote: 'Save Quick Note',
    organization: 'Organization',
    noteDetails: 'Note Details',
    provisionUser: 'Provision User',
    closeForm: 'Close Form',
    legalName: 'Legal Name',
    enterpriseEmail: 'Enterprise Email',
    privilegeLevel: 'Privilege Level',
    finalConfirmation: 'Final Confirmation',
    removeUserWarning: 'Removing personnel revokes all system access.',
    executeRemoval: 'Execute Removal',
    exitDirectory: 'Exit Directory',
    activeIdentity: 'Active Identity',
    manageUnifiedAccounts: 'Manage Unified Strategic Accounts',
    newRegistration: 'New Registration',
    searchDirectory: 'Search directory...',
    unassigned: 'Unassigned',
    securityPerimeter: 'Security Perimeter',
    authorizedPersonnel: 'Authorized Personnel',
    archiveNote: 'Move to Archived',
    unarchiveNote: 'Restore Account',
    pinNote: 'Pin Note',
    unpinNote: 'Unpin Note',
    workspaceSettings: 'Workspace Configuration',
    showShortcuts: 'Show Customer Shortcuts',
    showChannels: 'Show Group Channels',
    showDMs: 'Show Direct Messages',
    appearance: 'Appearance',
    theme: 'System Theme',
    layout: 'Layout & Ordering',
    loginTitle: 'Login',
    loginSubtitle: 'Secure portal for team intelligence.',
    identityAccess: 'Personnel Selection',
    selectPersonnel: 'Select profile',
    securityToken: 'Password',
    initializeSession: 'Login',
    secureNode: 'Secure Access',
    userTiers: 'User Levels',
    knowledgeCount: 'Knowledge',
    onboardingTitle: 'Welcome to Nori',
    onboardingSubtitle: 'Enterprise Platform',
    whatAppHas: 'System Features',
    evalRoadmap: 'Platform Use',
    acknowledgeBtn: 'Start Using Nori',
    onboardingDesc: 'A secure repository for customer intelligence and team coordination.',
    profile: "Profile",
    full_name: "Full Name",
    enter_name: "Enter name...",
    sidebar_priority: "Sidebar Priority",
    shortcuts: "Shortcuts",
    dms: "Direct Messages",
    discard: "Discard",
    save_config: "Save Config",
    success: "Success",
    update_success: "Profile updated successfully!",
    error: "Error",
    update_failed: "Could not update profile. Please try again.",
    permission_denied: "Permission Denied",
    camera_permission_msg: "Sorry, we need camera roll permissions to change your avatar.",
    selectDate: 'Select Date',
    deadline: 'Deadline',
    noMatchingRecords : 'No matching records in this view',
    search_intel_records: 'Search intel records...',
    search_pinned_records: 'Search pinned records...',
    search_archived_records: 'Search archived records...',
    replying_to_comment_thread : 'Replying to comment thread',
    replying_to_original_note: 'Replying to original note',
    describe_situational_response: 'Describe situational response...',
    select_personnel: 'Select Personnel',
  },
  vi: {
    dashboard: 'Bảng điều khiển',
    customers: 'Khách hàng',
    exploreAll: 'Khám phá tất cả',
    customerDirectory: 'Danh bạ khách hàng',
    totalRecords: 'Tổng số bản ghi',
    activeFilters: 'Bộ lọc hiện tại',
    allStatuses: 'Tất cả trạng thái',
    channels: 'Kênh thảo luận',
    directMessages: 'Tin nhắn trực tiếp',
    quickNote: 'Ghi chú nhanh',
    personalNotes: 'Ghi chú cá nhân',
    searchPlaceholder: 'Tìm kiếm kho lưu trữ...',
    logout: 'Đăng xuất',
    accessLevel: 'Mức độ truy cập',
    personnelDirectory: 'Danh bạ nhân sự',
    systemLive: 'Hệ thống hoạt động',
    activityFeed: 'Bảng tin hoạt động',
    files: 'Tài liệu',
    archived: 'Đã lưu trữ',
    captureNote: 'Ghi lại ghi chú...',
    saveArchive: 'Lưu ghi chú vào kho lưu trữ',
    privateEntry: 'Nội dung riêng tư',
    caseStatus: 'Trạng thái',
    urgency: 'Độ khẩn cấp',
    assignTask: 'Giao việc',
    recentActivity: 'Hoạt động gần đây',
    activePersonnel: 'Nhân sự trực tuyến',
    criticalDeadlines: 'Hạn chót quan trọng',
    language: 'Ngôn ngữ',
    vietnamese: 'Tiếng Việt',
    english: 'Tiếng Anh',
    postReply: 'Phản hồi',
    editNote: 'Sửa ghi chú',
    saveNote: 'Lưu ghi chú',
    discardChanges: 'Hủy thay đổi',
    revisionHistory: 'Lịch sử chỉnh sửa',
    privateNote: 'Ghi chú riêng tư',
    open: 'Đang mở',
    resolved: 'Đã giải quyết',
    closed: 'Đã đóng',
    low: 'Thấp',
    medium: 'Trung bình',
    high: 'Cao',
    urgent: 'Khẩn cấp',
    alerts: 'Thông báo',
    clearAll: 'Xóa tất cả',
    noAlerts: 'Không có thông báo mới',
    intelligenceLogs: 'Nhật ký thông tin',
    urgentAlerts: 'Cảnh báo khẩn',
    systemHealth: 'Tình trạng hệ thống',
    liveStream: 'Trực tiếp',
    noActivity: 'Không có hoạt động nào.',
    logBy: 'Ghi chép bởi',
    noDeadlines: 'Không có hạn chót nào.',
    noAccessibleCustomers: 'Không tìm thấy khách hàng khả dụng.',
    cancel: 'Hủy bỏ',
    saveQuickNote: 'Lưu ghi chú nhanh',
    organization: 'Tổ chức',
    noteDetails: 'Chi tiết ghi chú',
    provisionUser: 'Cấp quyền nhân sự',
    closeForm: 'Đóng biểu mẫu',
    legalName: 'Tên pháp lý',
    enterpriseEmail: 'Email doanh nghiệp',
    privilegeLevel: 'Cấp độ đặc quyền',
    finalConfirmation: 'Xác nhận cuối cùng',
    removeUserWarning: 'Xóa nhân sự sẽ thu hồi toàn bộ quyền truy cập hệ thống.',
    executeRemoval: 'Thực hiện xóa',
    exitDirectory: 'Thoát danh bạ',
    activeIdentity: 'Danh tính hoạt động',
    manageUnifiedAccounts: 'Quản lý tài khoản chiến lược hợp nhất',
    newRegistration: 'Đăng ký mới',
    searchDirectory: 'Tìm kiếm danh bạ...',
    unassigned: 'Chưa phân công',
    securityPerimeter: 'Phạm vi bảo mật',
    authorizedPersonnel: 'Nhân sự được ủy quyền',
    archiveNote: 'Chuyển sang Lưu trữ',
    unarchiveNote: 'Khôi phục tài khoản',
    pinNote: 'Ghim ghi chú',
    unpinNote: 'Bỏ ghim ghi chú',
    workspaceSettings: 'Cấu hình không gian làm việc',
    showShortcuts: 'Hiển thị Phím tắt Khách hàng',
    showChannels: 'Hiển thị Kênh Thảo luận',
    showDMs: 'Hiển thị Tin nhắn Trực tiếp',
    appearance: 'Giao diện',
    theme: 'Chủ đề hệ thống',
    layout: 'Bố cục & Sắp xếp',
    loginTitle: 'Đăng nhập',
    loginSubtitle: 'Cổng truy cập bảo mật cho đội ngũ.',
    identityAccess: 'Chọn nhân sự',
    selectPersonnel: 'Chọn hồ sơ',
    securityToken: 'Mật khẩu',
    initializeSession: 'Đăng nhập',
    secureNode: 'Truy cập Bảo mật',
    userTiers: 'Cấp độ Người dùng',
    knowledgeCount: 'Tri thức',
    onboardingTitle: 'Chào mừng đến Nori',
    onboardingSubtitle: 'Nền tảng Doanh nghiệp',
    whatAppHas: 'Tính năng Hệ thống',
    evalRoadmap: 'Sử dụng Nền tảng',
    acknowledgeBtn: 'Bắt đầu sử dụng Nori',
    onboardingDesc: 'Kho lưu trữ bảo mật cho tình báo khách hàng và phối hợp nhóm.',
    profile: "Hồ sơ",
    full_name: "Họ và Tên",
    enter_name: "Nhập tên...",
    sidebar_priority: "Ưu tiên thanh bên",
    shortcuts: "Lối tắt",
    dms: "Tin nhắn",
    discard: "Hủy bỏ",
    save_config: "Lưu cấu hình",
    success: "Thành công",
    update_success: "Cập nhật hồ sơ thành công!",
    error: "Lỗi",
    update_failed: "Không thể cập nhật hồ sơ. Vui lòng thử lại.",
    permission_denied: "Từ chối quyền",
    camera_permission_msg: "Xin lỗi, chúng tôi cần quyền truy cập thư viện ảnh để thay đổi ảnh đại diện.",
    selectDate: 'Chọn ngày',
    deadline: 'Hạn chót',
    noMatchingRecords: 'Không tìm thấy bản ghi phù hợp.',
    search_intel_records: 'Tìm kiếm bản ghi thông tin...',
    search_pinned_records: 'Tìm kiếm bản ghi đã ghim...',
    search_archived_records: 'Tìm kiếm bản ghi đã lưu trữ...',
    replying_to_comment_thread :'Trả lời chuỗi bình luận',
    replying_to_original_note: 'Trả lời ghi chú gốc',
    describe_situational_response: 'Mô tả phản ứng tình huống...',
    select_personnel: 'Chọn nhân sự',
  }
};

export const DEFAULT_PREFS: SidebarPrefs = {
  showShortcuts: true,
  showChannels: true,
  showDMs: true,
  order: ['shortcuts', 'channels', 'dms'],
  theme: 'emerald',
  dashboardPrefs: {
    showStats: true,
    showPinnedSection: true,
    showRecentActivity: true,
    showActivePersonnel: true,
    showDeadlines: true,
    order: ['stats', 'pinned', 'activity', 'personnel', 'deadlines']
  }
};

export const THEMES = {
  emerald: { primary: '#10b981', dark: '#059669', label: 'Emerald Isle' },
  sapphire: { primary: '#2563eb', dark: '#1d4ed8', label: 'Deep Sapphire' },
  midnight: { primary: '#334155', dark: '#1e293b', label: 'Midnight Slate' },
  ruby: { primary: '#e11d48', dark: '#be123c', label: 'Ruby Crimson' },
  'pink-pastel': { primary: '#f472b6', dark: '#db2777', label: 'Pink Pastel' },
  'panda-soft': { primary: '#fb923c', dark: '#ea580c', label: 'Panda Soft' },
  'cyber-circuit': { primary: '#06b6d4', dark: '#0891b2', label: 'Cyber Circuit' },
  'sakura-dream': { primary: '#fda4af', dark: '#f43f5e', label: 'Sakura Dream' }
};

export const MOCK_TEAM_MEMBERS: TeamMember[] = [
  { id: 'id-supervisor', name: 'Hieu Nguyen', email: 'hieu.n@thabico.group', role: UserRole.SUPERVISOR, status: 'online', avatar: 'https://i.pravatar.cc/150?u=hieu', sidebarPrefs: DEFAULT_PREFS },
  { id: 'id-manager', name: 'Trang Le', email: 'trang.l@thabico.group', role: UserRole.MANAGER, status: 'online', avatar: 'https://i.pravatar.cc/150?u=trang', sidebarPrefs: { ...DEFAULT_PREFS, theme: 'sakura-dream' } },
  { id: 'id-sales', name: 'Duy Pham', email: 'duy.p@thabico.group', role: UserRole.SALE, status: 'away', avatar: 'https://i.pravatar.cc/150?u=duy', sidebarPrefs: { ...DEFAULT_PREFS, theme: 'midnight' } },
  { id: 'id-sales-2', name: 'Linh Vo', email: 'linh.v@thabico.group', role: UserRole.SALE, status: 'online', avatar: 'https://i.pravatar.cc/150?u=linh', sidebarPrefs: DEFAULT_PREFS },
  { id: 'id-logistics', name: 'Bao Hoang', email: 'bao.h@thabico.group', role: UserRole.LOGISTICS, status: 'offline', avatar: 'https://i.pravatar.cc/150?u=bao', sidebarPrefs: DEFAULT_PREFS },
  { id: 'id-onboard-test', name: 'Mai Nguyen', email: 'mai.n@thabico.group', role: UserRole.ONBOARD, status: 'offline', avatar: 'https://i.pravatar.cc/150?u=mai', sidebarPrefs: { ...DEFAULT_PREFS, theme: 'pink-pastel' } },
];

export const MOCK_CUSTOMERS: Customer[] = [
  { id: '1', name: 'Minh Tran', company: 'Green Paddy Farms', email: 'minh.tran@greenpaddy.vn', status: 'active', lastActivity: Date.now() - 3600000, isPublic: false, allowedUserIds: ['id-sales', 'id-supervisor'] },
  { id: '2', name: 'Lan Nguyen', company: 'Sài Gòn Agri-Tech', email: 'lan.nguyen@saigonagri.vn', status: 'active', lastActivity: Date.now() - 7200000, isPublic: false, allowedUserIds: ['id-sales-2', 'id-supervisor', 'id-manager'] },
  { id: '3', name: 'Phuc Hoang', company: 'Mekong Delta Fruits', email: 'phuc.hoang@mekongfruits.com', status: 'pending', lastActivity: Date.now() - 86400000, isPublic: false, allowedRoles: [UserRole.SUPERVISOR, UserRole.MANAGER] },
  { id: '4', name: 'Anh Vo', company: 'Đà Lạt Organics', email: 'anh.vo@dalatorganics.vn', status: 'active', lastActivity: Date.now() - 120000, isPublic: true },
  { id: '5', name: 'Tuan Le', company: 'Northern Highland Tea', email: 'tuan.le@highlandtea.vn', status: 'active', lastActivity: Date.now(), isPublic: true },
];

export const INITIAL_LOGS: CustomerLog[] = [
  {
    id: 'l1',
    customerId: '1',
    authorId: 'id-supervisor',
    authorName: 'Hieu Nguyen',
    authorRole: UserRole.SUPERVISOR,
    content: 'Observed unusual equipment movement at Green Paddy facilities. Potential expansion or audit prep. Keep monitoring @Duy.',
    category: 'update',
    logType: 'General',
    timestamp: Date.now() - 172800000,
    isPrivate: true,
    priority: 'high',
    status: 'open',
    attachments: [
      { id: 'att-1', name: 'Site_Survey_Report.pdf', type: 'pdf', url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', size: 102400 }
    ]
  },
  {
    id: 'l2',
    customerId: '1',
    authorId: 'id-supervisor',
    authorName: 'Hieu Nguyen',
    authorRole: UserRole.SUPERVISOR,
    content: 'CRITICAL: Quality check passed for Jasmine Rice Batch #902. Documentation verified.',
    category: 'update',
    logType: 'Document',
    timestamp: Date.now() - 86400000,
    isPrivate: false,
    isPinned: true,
    priority: 'high',
    status: 'open',
    dueDate: Date.now() + 86400000,
    assigneeId: 'id-sales',
    attachments: [
      { id: 'att-2', name: 'Batch_902_Verify.png', type: 'image', url: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80', size: 450000 }
    ]
  },
  {
    id: 'l3',
    customerId: '4',
    authorId: 'id-sales',
    authorName: 'Duy Pham',
    authorRole: UserRole.SALE,
    content: 'Dalat Organics Site Visit: Captured video of the new irrigation system in action.',
    category: 'note',
    logType: 'General',
    timestamp: Date.now() - 7200000,
    isPrivate: false,
    priority: 'medium',
    status: 'open',
    attachments: [
      { id: 'att-3', name: 'Irrigation_System_Demo.mp4', type: 'video', url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4', size: 15000000 }
    ]
  },
  {
    id: 'l4',
    customerId: '2',
    authorId: 'id-supervisor',
    authorName: 'Hieu Nguyen',
    authorRole: UserRole.SUPERVISOR,
    content: 'Confidential: Financial review of Sài Gòn Agri-Tech. High stability noted.',
    category: 'quick_note',
    logType: 'Price',
    timestamp: Date.now() - 3600000,
    isPrivate: true,
    priority: 'low',
    status: 'open',
    attachments: [
      { id: 'att-4', name: 'Financial_Spreadsheet.pdf', type: 'pdf', url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', size: 55000 }
    ]
  },
  {
    id: 'l5',
    customerId: '5',
    authorId: 'id-supervisor',
    authorName: 'Hieu Nguyen',
    authorRole: UserRole.SUPERVISOR,
    content: 'Personal Note: Tuan Le mentioned interest in expanding to high-altitude specialized teas by Q4. Need to prep strategy.',
    category: 'note',
    logType: 'General',
    timestamp: Date.now() - 1800000,
    isPrivate: true,
    priority: 'medium',
    status: 'open',
    attachments: [
       { id: 'att-5', name: 'Specialty_Tea_Proposal.pdf', type: 'pdf', url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', size: 89000 }
    ]
  }
];

export const INITIAL_CHANNELS: ChatChannel[] = [
  { id: 'ch-1', name: 'General Feed', description: 'Daily coordination for Agri-Logistics', type: 'general' },
  { id: 'ch-2', name: 'Harvest Urgent', description: 'Critical harvest season updates', type: 'urgent' },
  { id: 'ch-3', name: 'Tech Support', description: 'Internal platform helpdesk', type: 'support' },
];

export const INITIAL_TEAM_CHAT: ChatMessage[] = [
  { id: 'm1', role: 'user', authorId: 'id-supervisor', authorName: 'Hieu Nguyen', authorRole: UserRole.SUPERVISOR, text: 'Morning team! Let\'s stay focused on the Mekong Delta Fruits audit today.', timestamp: Date.now() - 3600000, channelId: 'ch-1' },
  { id: 'm2', role: 'user', authorId: 'id-sales', authorName: 'Duy Pham', authorRole: UserRole.SALE, text: '@Hieu I\'ve updated the Dalat field notes. @Linh did you check Saigon Agri yet?', timestamp: Date.now() - 1800000, channelId: 'ch-1' },
  { id: 'm3', role: 'user', authorId: 'id-manager', authorName: 'Trang Le', authorRole: UserRole.MANAGER, text: 'Hey Hieu, just sent you the confidential audit for Green Paddy.', timestamp: Date.now() - 1200000, recipientId: 'id-supervisor' },
];

export const INITIAL_NOTIFICATIONS: Notification[] = [
  { id: 'n1', recipientId: 'id-sales', senderName: 'Hieu Nguyen', type: 'assignment', text: 'Assigned you to Green Paddy Jasmine logistics.', timestamp: Date.now() - 172800000, read: false, targetCustomerId: '1' },
  { id: 'n2', recipientId: 'id-manager', senderName: 'Linh Vo', type: 'mention', text: 'Mentioned you in Sài Gòn Agri-Tech notes.', timestamp: Date.now() - 3600000, read: false, targetCustomerId: '2' },
  { id: 'n3', recipientId: 'id-sales-2', senderName: 'Duy Pham', type: 'mention', text: 'Hey @Linh did you check Saigon Agri?', timestamp: Date.now() - 1800000, read: false, link: 'team-chat' },
  { id: 'n4', recipientId: 'id-supervisor', senderName: 'Trang Le', type: 'message', text: 'Hey Hieu, just sent you the confidential audit...', timestamp: Date.now() - 1200000, read: false, link: 'team-chat' }
];
export const LOG_TYPE_STYLES: Record<string, { bg: string; text: string; border: string }> = {
  PO: { bg: '#f5f3ff', text: '#4c1d95', border: '#c4b5fd' },        // Text 900, Border 300
  Complaint: { bg: '#fff1f2', text: '#881337', border: '#fb7185' }, // Text 900, Border 400
  Document: { bg: '#f0fdfa', text: '#064e3b', border: '#2dd4bf' },  // Text 900, Border 400
  Price: { bg: '#fffbeb', text: '#78350f', border: '#fbbf24' },     // Text 900, Border 400
  General: { bg: '#f1f5f9', text: '#0f172a', border: '#94a3b8' },   // Text 900, Border 400
};
export const ROLE_CONFIG = {
  [UserRole.SUPERVISOR]: { 
    label: 'Supervisor', 
    bgColor: '#d1fae5', 
    textColor: '#047857', 
    borderColor: '#a7f3d0', 
    canChat: true, 
    canManageAccess: true 
  },
  [UserRole.MANAGER]: { 
    label: 'Manager', 
    bgColor: '#dcfce7', 
    textColor: '#15803d', 
    borderColor: '#bbf7d0', 
    canChat: true, 
    canManageAccess: true 
  },
  [UserRole.SALE]: { 
    label: 'Sales Agent', 
    bgColor: '#f0fdf4', 
    textColor: '#166534', 
    borderColor: '#dcfce7', 
    canChat: true, 
    canManageAccess: false 
  },
  [UserRole.LOGISTICS]: { 
    label: 'Logistics', 
    bgColor: '#eff6ff', 
    textColor: '#1d4ed8', 
    borderColor: '#dbeafe', 
    canChat: false, 
    canManageAccess: false 
  },
  [UserRole.ONBOARD]: { 
    label: 'Awaiting Activation', 
    bgColor: '#fff1f2', 
    textColor: '#be123c', 
    borderColor: '#ffe4e6', 
    canChat: false, 
    canManageAccess: false 
  },
  [UserRole.VIEWER]: { 
    label: 'Viewer', 
    bgColor: '#f8fafc', 
    textColor: '#475569', 
    borderColor: '#e2e8f0', 
    canChat: false, 
    canManageAccess: false 
  },
};
